### ISSUE TITLE
Cannot access openatv enigma 2

### ISSUE THREAD

**Issue by CoolFX2011** [dpembo/e2stream#10]
Installed fine on my Samsung H series. After setting the ip of my gigablue, e2stream can't find my box. Openwebif is running fine on port 80 with no authentication. Tested on my laptop and everything works. Please help... Don't know what to do more. Thanks.

**Comment by CoolFX2011** [comment]
Error 500 is the error I've got

**Comment by dpembo** [comment]
unfortunately this is impossible for me to replciate - you could turn on the debug mode (tools button on remote) to see if this gives any clues, and perhaps try a mobile phone app connection to see if this can talk.
