### ISSUE TITLE
time region

### ISSUE THREAD

**Issue by ghost** [dpembo/e2stream#11]
Hi, I like E2Stream very much. However, the displayed time in E2Stream isn't correct. It's 2 hours behind our local time. I'm located in The Netherlands. Can you add a setting for changing timesetting depending on region (CET)?

Thank you!

**Comment by dpembo** [comment]
I'll take a look at this to see if I can determine the initial time from the E2 box.  I'm not doing anything specific with timezones, so I guess it's either stuck in UTC (GMT) or something more unusual is going on.  I've never noticed an issue when we're in British Summer time.

**Comment by ghost** [comment]
Thank you, much appreciated! If I can correct the time with +2 hours my problem is fixed ;-) Manually or automatically, no problem.

**Comment by retrofan1979** [comment]
@dpembo:
Any update about this issue?
See page 29 of the DVB specifications: https://www.dvb.org/resources/public/standards/a38_dvb-si_specification.pdf

Thanks!

**Comment by retrofan1979** [comment]
Also see chapter 5.2.5.

**Comment by dpembo** [comment]
I'm unable to recreate this - the app sets the timezone according to the tv, and everything works fine, there's no hardcoded timezone, and in fact the emulator runs in a different timezone than mine and it all still works correctly.  Also - there's a number of european users using this and no one has complained about this.

Is it possible your TV, or your E2 box are in the wrong timezone?

**Comment by dpembo** [comment]
to give you a further view
E2 returns a program time as a number of milli seconds since epoch (i.e a UTC Date Time)
This, and the time are both put into a date and returned in a current timezone date string for display.  I'm guessing that the timezone on your TV isn't quite right and thats what causes the javascript to pick up the wrong timezone.  Does your Time differ from what is showing in the now next, or are both in the wrong time zone?

**Comment by ghost** [comment]
@dpembo 
My fault. I thought the time was extracted from DVB stream, but indeed my Samsung Blu-ray has a timezone setting, somewhat hidden, so I didn't see it earlier. I'm very happy! I will donate you for your great work. I like your app! So, this issue can be closed :-)

**Comment by dpembo** [comment]
Perfect - thanks :)
