### ISSUE TITLE
Support for D-Series Samsung TV's

### ISSUE THREAD

**Issue by gdhgdhgdh** [dpembo/e2stream#8]
Hi,

Thanks for creating this app - I found it while searching for something entirely different (trying to use Amazon Video on my 'old' (!) D8000 telly.

V 6.5 of the app installs fine and loads the channel list + EPG fine but I can't stream anything. Default mode says 'Buffering...' and Legacy mode gives me fullscreen exclamation marks with wordy 'can't open file'. 

I can't remember the exact wording as a) the TV is at the other end of the house and b) I'm feeling very refreshed from gin + tonic :)

Is there likely to be any support for these ancient 2011 screens? My eyes roll when I think how much I paid for it 4 years ago!

Cheers,
Gavin.

**Comment by ghost** [comment]
This issue affects me also, can we please get developer analysis on this? Looking through the code the lines affected here are:
e2stream-installer.jar\e2streamassets.jar\e2stream.pkg\Javascript\VideoOverlay.js

**...
if (time instanceof PlayTime) {
...
} else {
// Not a date object
if(Main.playerObj!=null && Main.playerObj.name()=='Default')timeHTML = "buffering... please wait!";
else timeHTML="";
}
widgetAPI.putInnerHTML(timeElement, timeHTML);**

Can someone say why it displays a 'please wait' message to screen when its not doing anything?
What is the PlayTime instance here?
If the instanceof check was removed would it function for D models?

Brendan

**Comment by dpembo** [comment]
The D series media player simply can't understand the stream format from the box.
If your E2 can transcode, turn that on, and turn the legacy player on, and you stand a good chance of it playing something as transcoding changes it to a format that the TV understands.

**Comment by dpembo** [comment]
nothing more I can do
